dist: trusty
sudo: enabled
language: perl
perl:
- '5.26'
- '5.24'
- '5.18'
env:
  global:
    secure: ggwWFNFIxy15E3QOtLsjaUA2L9MX/bn8r5jKEDyZPC6G5Qkx9oruM3fq5vHgYdKGmaVZU1OzO3y1m94X/T+QMsDw53eu0nf7hs6xWKPalpZ1/KsD53CacDdqolwtUowG2RcMOwB9IJ2DkwQ/FMuCJ9flgoHw+4FGCQmrt9v4KgQecnUDoHKPm8rM+MxcGGzaiPP0INWEqLPKbeQ+1dgrUCIIDCMM22JYn94MlwiQYFBEUwwEh/PXFvTgzE1kzdGvJ4hIq6k3+Nu6e2XAz7YmEMgNX9g0v92D3dMKOFyigIUnt6pt4Ft731EziP4OCz54y61Qw7ggCRqbfU4vbPl0h3okBokFdfSla3V9NBo+hY0hRBippT3gYnn/ZtDtEybQr2okCFnUK+ltDYjO0teQ8T2r6fkevSvkhEobiycY6lLPjj298r/K9JZfAjS+KzAjA9SNAnwF4WZbcKCGVXUy/clRgl4ohFxwDgf7uj+xDLuYRhGM8Kcn90ol17pU3tcbWX+HxCMRg09vEYmSMChU3toHyyUKzOtSer18n9hn+G3XuaELJoqLwcjIdATCtZDmCiob3rsj1UPcx4gmu1mYhBqcMB8X75GCkfliamIsHlsz1gvJ4Y36/NTm/N1peTRKxRyj7j5CNLKO2xtEMNEGF3NnWVzHCAPHsZY9RoW0VQY=
git:
  depth: false
before_install:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git config --global push.default simple
- git remote set-url origin https://${GH_API_KEY}@github.com/RFD-FHEM/UnitTest.git
- wget -qO - http://debian.fhem.de/archive.key | sudo apt-key add -
- echo "deb http://debian.fhem.de/nightly/ /" | sudo tee -a /etc/apt/sources.list
install:
- sudo apt-get update -qq
- cpanm File::Find File::Basename Mock::Sub Test::More Test::Device::SerialPort JSON
  --notest
- sudo apt-get install fhem -qq -y
- sudo chown travis -R /opt/fhem
script:
- make test -j2
- make fhem_kill
- ./build_controls_list.sh
- git commit -m "Travis automatic update controls file. Build (${TRAVIS_BUILD_NUMBER})
  [skip ci]" ./controls_unittest.txt || true
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ $TRAVIS_JOB_NUMBER == *.1 ]]; then
  git push origin HEAD:$TRAVIS_BRANCH ; fi
